title: A Human in the Loop
email: jamie.s.roszel@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  "A Human in the Loop" chronicles one content developer's journey to stay ahead 
  of the curve, exploring new software projects and pushing creative boundaries 
  in a world of rapidly evolving technology.
baseurl: "/my-blog" # required because your site is at username.github.io/my-blog
url: "https://jamieroszel22.github.io" # your GitHub Pages URL

# Social links
github_username: jamieroszel22

disqus:
  shortname: humanintheloop

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Customize the site
show_excerpts: true # shows post excerpts on home page
minima:
  date_format: "%b %-d, %Y"
  social_links:
    - title: LinkedIn Profile
      icon: linkedin
      url: "https://www.linkedin.com/in/jamie-roszel-59a2a395/" # Replace with your actual LinkedIn profile URL

# Define header pages
header_pages:
  - about.md
  - categories.md

navbar_links:
  - title: Portfolio
    url: https://jamieroszel.com

# SASS settings for styling
sass:
  style: compressed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/